# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectaproductoftheday():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectaproductofthedayinthecategoryBWAandaccessories(self):
    # Test name: Select a product of the day in the category BWA and accessories
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="ДБЖ та аксесуари"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"ДБЖ та аксесуари\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="ДБЖ та аксесуари"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"ДБЖ та аксесуари\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategoryEverythingforCybersport(self):
    # Test name: Select a product of the day in the category Everything for Cybersport
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Все для кіберспорту"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Все для кіберспорту\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Все для кіберспорту"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Все для кіберспорту\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategoryPCaccessories(self):
    # Test name: Select a product of the day in the category PC accessories
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Комплектуючі для ПК"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Комплектуючі для ПК\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Комплектуючі для ПК"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Комплектуючі для ПК\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategoryPCperipherals(self):
    # Test name: Select a product of the day in the category PC peripherals
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Периферія для ПК"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Периферія для ПК\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Периферія для ПК"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Периферія для ПК\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategoryServicesandTradein(self):
    # Test name: Select a product of the day in the category Services and Trade-in
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Послуги та Trade-In"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Послуги та Trade-In\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Послуги та Trade-In"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Послуги та Trade-In\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategorylaptops(self):
    # Test name: Select a product of the day in the category laptops
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()='Ноутбуки']/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\'Ноутбуки\']/ancestor::li").click()
    # 3 | click | xpath=//i[text()='Ноутбуки']/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\'Ноутбуки\']/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategorynetworkhardware(self):
    # Test name: Select a product of the day in the category network hardware
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Мережеве обладнання"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Мережеве обладнання\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Мережеве обладнання"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Мережеве обладнання\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategorymonitors(self):
    # Test name: Select a product of the day in the category monitors
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Монітори"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Монітори\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Монітори"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Монітори\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
  def test_selectaproductofthedayinthecategorypc(self):
    # Test name: Select a product of the day in the category pc
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[text()="Комп'ютери"]/ancestor::li | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Комп\'ютери\"]/ancestor::li").click()
    # 3 | click | xpath=//i[text()="Комп'ютери"]/ancestor::li/*//div[@class='b-i-product-name']/a | 
    self.driver.find_element(By.XPATH, "//i[text()=\"Комп\'ютери\"]/ancestor::li/*//div[@class=\'b-i-product-name\']/a").click()
  
