# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcases():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addaproducttothebasketwithonefilterselected(self):
    # Test name: Add a product to the basket with one filter selected
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[contains(.,'Ноутбуки')] | 
    self.driver.find_element(By.XPATH, "//i[contains(.,\'Ноутбуки\')]").click()
    # 3 | click | xpath=//a[contains(@href, 'https://telemart.ua/ua/laptops/')] | 
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'https://telemart.ua/ua/laptops/\')]").click()
    # 4 | click | xpath=//label[contains(.,'Акція')] | 
    self.driver.find_element(By.XPATH, "//label[contains(.,\'Акція\')]").click()
    # 5 | click | xpath=//a[contains(@href, 'https://telemart.ua/ua/laptops/filter/t_action/')] | 
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'https://telemart.ua/ua/laptops/filter/t_action/\')]").click()
    # 6 | click | xpath=//div[contains(@class,'cards__item product_wrapper')][1]/*//a | 
    self.driver.find_element(By.XPATH, "//div[contains(@class,\'cards__item product_wrapper\')][1]/*//a").click()
    # 7 | click | xpath=//div[@class='b-product-wtbox']/*//a[contains(text(),'Купити')] | 
    self.driver.find_element(By.XPATH, "//div[@class=\'b-product-wtbox\']/*//a[contains(text(),\'Купити\')]").click()
  
  def test_addaproducttothebasketwithtwofiltersselected(self):
    # Test name: Add a product to the basket with two filters selected
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[contains(.,'Ноутбуки')] | 
    self.driver.find_element(By.XPATH, "//i[contains(.,\'Ноутбуки\')]").click()
    # 3 | click | xpath=//a[contains(@href, 'https://telemart.ua/ua/laptops/')] | 
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'https://telemart.ua/ua/laptops/\')]").click()
    # 4 | click | xpath=*//a[@title='Для навчання та офісу'] | 
    self.driver.find_element(By.XPATH, "*//a[@title=\'Для навчання та офісу\']").click()
    # 5 | click | xpath=//label[contains(.,'Готовий до відправки')] | 
    self.driver.find_element(By.XPATH, "//label[contains(.,\'Готовий до відправки\')]").click()
    # 6 | click | xpath=//div[@class='b-link']/a | 
    self.driver.find_element(By.XPATH, "//div[@class=\'b-link\']/a").click()
    # 7 | click | xpath=//div[contains(@class,'cards__item product_wrapper')][1]/*//a | 
    self.driver.find_element(By.XPATH, "//div[contains(@class,\'cards__item product_wrapper\')][1]/*//a").click()
    # 8 | click | xpath=//div[@class='b-product-wtbox']/*//a[contains(text(),'Купити')] | 
    self.driver.find_element(By.XPATH, "//div[@class=\'b-product-wtbox\']/*//a[contains(text(),\'Купити\')]").click()
  
  def test_addproductstothecomparisonlist(self):
    # Test name: Add products to the comparison list
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//i[contains(.,'Ноутбуки')] | 
    self.driver.find_element(By.XPATH, "//i[contains(.,\'Ноутбуки\')]").click()
    # 3 | click | xpath=//a[contains(@href, 'https://telemart.ua/ua/laptops/')] | 
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'https://telemart.ua/ua/laptops/\')]").click()
    # 4 | click | xpath=//div[contains(@class,'b-catalog-row-plate ')]/div[position()=1]//a[@class='b-link-add2compare'] | 
    self.driver.find_element(By.XPATH, "//div[contains(@class,\'b-catalog-row-plate \')]/div[position()=1]//a[@class=\'b-link-add2compare\']").click()
    # 5 | click | xpath=//div[contains(@class,'b-catalog-row-plate ')]/div[position()=2]//a[@class='b-link-add2compare'] | 
    self.driver.find_element(By.XPATH, "//div[contains(@class,\'b-catalog-row-plate \')]/div[position()=2]//a[@class=\'b-link-add2compare\']").click()
    # 6 | click | xpath=//div[@class='b-header-bot-side']//a[@class='b-link-compare'] | 
    self.driver.find_element(By.XPATH, "//div[@class=\'b-header-bot-side\']//a[@class=\'b-link-compare\']").click()
  
  def test_checkstatusoforderwithinvaliddata(self):
    # Test name: Check status of order with invalid data
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//img[contains(@src,'https://img.telemart.ua/img/banners_index/banner_ukr_9.png')] | 
    self.driver.find_element(By.XPATH, "//img[contains(@src,\'https://img.telemart.ua/img/banners_index/banner_ukr_9.png\')]").click()
    # 3 | click | xpath=//input[@name='id_order'] | 
    self.driver.find_element(By.XPATH, "//input[@name=\'id_order\']").click()
    # 4 | type | xpath=//input[@name='id_order'] | 55545466
    self.driver.find_element(By.XPATH, "//input[@name=\'id_order\']").send_keys("55545466")
    # 5 | click | xpath=//input[@id='popupInputRegPhone'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'popupInputRegPhone\']").click()
    # 6 | type | xpath=//input[@id='popupInputRegPhone'] | 0634425312
    self.driver.find_element(By.XPATH, "//input[@id=\'popupInputRegPhone\']").send_keys("0634425312")
    # 7 | click | xpath=//button[contains(.,'Перевірити статус')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Перевірити статус\')]").click()
  
  def test_checkthestatusofanorderwithinvaliddata(self):
    # Test name: Check the status of an order with valid data
    # Step # | name | target | value
    # 1 | open | https://telemart.ua/ua/ | 
    self.driver.get("https://telemart.ua/ua/")
    # 2 | click | xpath=//img[contains(@src,'https://img.telemart.ua/img/banners_index/banner_ukr_9.png')] | 
    self.driver.find_element(By.XPATH, "//img[contains(@src,\'https://img.telemart.ua/img/banners_index/banner_ukr_9.png\')]").click()
    # 3 | click | xpath=//input[@name='id_order'] | 
    self.driver.find_element(By.XPATH, "//input[@name=\'id_order\']").click()
    # 4 | type | xpath=//input[@name='id_order'] | 34567355
    self.driver.find_element(By.XPATH, "//input[@name=\'id_order\']").send_keys("34567355")
    # 5 | click | xpath=//input[@id='popupInputRegPhone'] | 
    self.driver.find_element(By.XPATH, "//input[@id=\'popupInputRegPhone\']").click()
    # 6 | type | xpath=//input[@id='popupInputRegPhone'] | 653425242
    self.driver.find_element(By.XPATH, "//input[@id=\'popupInputRegPhone\']").send_keys("653425242")
    # 7 | click | xpath=//button[contains(.,'Перевірити статус')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Перевірити статус\')]").click()
  
